#!/bin/bash
# 
# (lcalitz) Back up all databases to the dev site. Meant to be called
#   daily basis from crontab.

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

# Use the automysqlbackup config for file locations, etc.
source /etc/automysqlbackup/automysqlbackup.conf

# Backup the database
automysqlbackup

# Get rid of old database backup files - keep monthlies for one year,
# weeklies for three months
find $BACKUPDIR/monthly -type f -mtime +366 -exec rm {} \;
find $BACKUPDIR/weekly -type f -mtime +93 -exec rm {} \;

