#!/bin/bash
#
# (lcalitz) Turn all references to www.porcfest.com and 
# porcfest.com in an FSP production DB into references to another site
#
# Call format:
#
#   chsite-pf <newsite> <infile> <outfile>
#   
#   newsite: Domain name for new site. Both www.porcfest.com and
#            freestateproject.com will be re-written to this name.
#   infile:  File containing production db dump
#   outfile: Result db dump to be uploaded to the new site db
#

cat $2 | \
  sed -e "s/www\.porcfest\.com/$(printf '%q' $1)/g" | \
  sed -e "s/porcfest\.com/$(printf '%q' $1)/g" > $3

